package dev.santo.tools

import dev.santo.vectorization.ReferenceResources

/**
 * Faithful offline port of the contest's `data-generator/main.c` request generator
 * (PCG32 + `gen_request` with `--randomize-payload-dates` + `normalize`). It emits
 * 14-dimension query vectors drawn from the SAME 3 profiles and randomized-date
 * distribution the contest uses, so an IVF recall measured against the float-exact
 * oracle on these queries reflects the real test — unlike the local `test-data.json`,
 * which was generated by our own pipeline (self-referential) and uses only fixed
 * dates, hiding the dim5-saturation tail (randomized last_tx → dim5 = 1.0).
 *
 * Only the vector-relevant fields are drawn (the per-field distributions are exact);
 * fields that never reach the vector are skipped. The seed is ours, not the contest's
 * — the FINAL test uses a different seed anyway, so absolute payloads are irrelevant;
 * the distribution is what matters for calibration.
 */
class OfficialOracle(seed: Long = 4242L, private val fraudRatio: Double = 0.5) {
    private val rng = Pcg32(seed)
    private val cfg = ReferenceResources.loadNormalization()
    private val mcc = ReferenceResources.loadMccRisk()

    /** Generates one randomized-date query vector (14 dims, same scheme as the refs). */
    fun nextVector(): DoubleArray {
        val p = pickProfile()
        val v = DoubleArray(14)

        val amount = round2(
            when (p) {
                LEGIT -> rng.range(10.0, 500.0)
                FRAUD -> rng.range(2000.0, 10000.0)
                else -> rng.range(400.0, 3000.0)
            }
        )
        val installments = when (p) {
            LEGIT -> rng.int(1, 4); FRAUD -> rng.int(6, 13); else -> rng.int(3, 8)
        }
        val hour = when (p) {
            LEGIT -> rng.int(8, 21); FRAUD -> rng.int(0, 7); else -> rng.int(6, 23)
        }
        // Randomized date (2026-03..2030-12); only y/m/d feed day-of-week (dim4).
        val year = rng.int(2026, 2031)
        val month = if (year == 2026) rng.int(3, 13) else rng.int(1, 13)
        val day = rng.int(1, 29)

        val custAvg = round2(
            when (p) {
                LEGIT -> rng.range(amount / 0.5, amount * 2.0)
                FRAUD -> rng.range(50.0, 300.0)
                else -> rng.range(100.0, 500.0)
            }
        )
        val txCount = when (p) {
            LEGIT -> rng.int(1, 6); FRAUD -> rng.int(8, 21); else -> rng.int(4, 12)
        }
        val mccRisk = when (p) {
            LEGIT -> mcc.riskOf(LEGIT_MCCS[rng.int(0, 4)])
            FRAUD -> mcc.riskOf(FRAUD_MCCS[rng.int(0, 3)])
            else -> mcc.riskOf(ALL_MCCS[rng.int(0, ALL_MCCS.size)])
        }
        val merchAvg = round2(
            when (p) {
                LEGIT -> rng.range(30.0, 500.0)
                FRAUD -> rng.range(20.0, 100.0)
                else -> rng.range(50.0, 300.0)
            }
        )
        val isOnline = when (p) {
            LEGIT -> rng.f64() < 0.3; FRAUD -> rng.f64() < 0.8; else -> rng.f64() < 0.5
        }
        val cardPresent = if (isOnline) false else rng.f64() < 0.9
        val kmHome = when (p) {
            LEGIT -> rng.range(0.0, 50.0); FRAUD -> rng.range(200.0, 1000.0); else -> rng.range(30.0, 400.0)
        }
        // Unknown-merchant flag (dim11): LEGIT picks a known merchant, FRAUD an
        // unknown one, BORDERLINE a coin flip — matches gen_request's merch_id logic.
        val unknownMerchant = when (p) {
            LEGIT -> false
            FRAUD -> true
            else -> rng.f64() >= 0.5
        }

        v[0] = clamp(amount / cfg.maxAmount)
        v[1] = clamp(installments / cfg.maxInstallments)
        v[2] = clamp((amount / custAvg) / cfg.amountVsAvgRatio)
        v[3] = hour / 23.0
        v[4] = dayOfWeekMon0(year, month, day) / 6.0
        // last_transaction present with prob 0.8; randomized seconds-back up to 10y,
        // so dim5 saturates to 1.0 for ~99.97% of those (the out-of-distribution tail).
        if (rng.f64() < 0.2) {
            v[5] = -1.0; v[6] = -1.0
        } else {
            val secsBack = 60.0 + (rng.u64() % TEN_YEARS_SECONDS).toDouble()
            v[5] = clamp((secsBack / 60.0) / cfg.maxMinutes)
            val lastKm = when (p) {
                LEGIT -> rng.range(0.0, 20.0); FRAUD -> rng.range(200.0, 1000.0); else -> rng.range(20.0, 300.0)
            }
            v[6] = clamp(lastKm / cfg.maxKm)
        }
        v[7] = clamp(kmHome / cfg.maxKm)
        v[8] = clamp(txCount / cfg.maxTxCount24h)
        v[9] = if (isOnline) 1.0 else 0.0
        v[10] = if (cardPresent) 1.0 else 0.0
        v[11] = if (unknownMerchant) 1.0 else 0.0
        v[12] = mccRisk
        v[13] = clamp(merchAvg / cfg.maxMerchantAvgAmount)
        return v
    }

    private fun pickProfile(): Int {
        val borderline = fraudRatio * 0.10
        val x = rng.f64()
        return when {
            x < 1.0 - fraudRatio -> LEGIT
            x < 1.0 - borderline -> FRAUD
            else -> BORDERLINE
        }
    }

    private fun clamp(x: Double) = x.coerceIn(0.0, 1.0)
    private fun round2(v: Double) = Math.round(v * 100.0) / 100.0

    /** Sakamoto, Monday=0..Sunday=6 (identical to the Vectorizer / official day_of_week). */
    private fun dayOfWeekMon0(year: Int, month: Int, day: Int): Int {
        val y = if (month < 3) year - 1 else year
        val dow = (y + y / 4 - y / 100 + y / 400 + DOW_T[month - 1] + day) % 7
        return (dow + 6) % 7
    }

    companion object {
        private const val LEGIT = 0
        private const val FRAUD = 1
        private const val BORDERLINE = 2
        private const val TEN_YEARS_SECONDS = 10L * 365 * 24 * 3600
        private val DOW_T = intArrayOf(0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4)
        private val LEGIT_MCCS = arrayOf("5411", "5812", "5912", "5311")
        private val FRAUD_MCCS = arrayOf("7995", "7801", "7802")
        // mcc_risk.json entry order (matches main.c's load_mcc iteration).
        private val ALL_MCCS =
            arrayOf("5411", "5812", "5912", "5944", "7801", "7802", "7995", "4511", "5311", "5999")
    }
}

/** PCG32 PRNG — bit-identical to the contest generator's `pcg32` / `rng_*` helpers. */
class Pcg32(seed: Long) {
    private var state = 0uL
    private var inc = (seed.toULong() shl 1) or 1uL

    init {
        next(); state += seed.toULong(); next()
    }

    fun next(): UInt {
        val s = state
        state = s * 6364136223846793005uL + inc
        val xorshifted = (((s shr 18) xor s) shr 27).toUInt()
        val rot = (s shr 59).toInt()
        return (xorshifted shr rot) or (xorshifted shl ((-rot) and 31))
    }

    /** Uniform double in [0,1], matching `rng_f64` (divide by UInt32 max). */
    fun f64(): Double = next().toLong().toDouble() / 4294967295.0
    fun range(lo: Double, hi: Double): Double = lo + f64() * (hi - lo)
    fun int(lo: Int, hi: Int): Int = lo + (next() % (hi - lo).toUInt()).toInt()
    fun u64(): Long = ((next().toULong() shl 32) or next().toULong()).toLong() and Long.MAX_VALUE
}
